version: '3.8'

services:
  frontend:
    image: caribeh/family-finance-frontend:latest
    container_name: family-finance-web
    ports:
      - "8080:80"
    environment:
      VITE_API_URL: http://localhost:3001/api
    networks:
      - family-finance-network

networks:
  family-finance-network:
    name: family-finance-network
    driver: bridge
    external: true
