version: '3.8'

services:
  postgres:
    image: caribeh/family-finance-db:latest
    container_name: family-finance-db
    environment:
      POSTGRES_DB: family_finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - family-finance-network

volumes:
  pgdata:

networks:
  family-finance-network:
    name: family-finance-network
    driver: bridge
